[package]
name = "roverup"
version = "0.1.0"
authors = ["Avery Harnish <avery@apollographql.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2"
thiserror = "1.0"
tracing = "0.1"
which = "4.0"
